import { primitiveColors as c } from './primitives';

export const semanticColors = {
  light: {
    background: c.plum100,
    backgroundGradient: [c.plum50, c.plum150, c.lightBackgroundEnd] as const,
    surface: c.white,
    surfaceGlass: c.glassWhite72,
    surfaceGlassStrong: c.glassWhite88,
    text: c.plum900,
    mutedText: c.plum700,
    primary: c.plum500,
    secondary: c.rose500,
    primarySoft: c.plum200,
    activeText: c.white,
    border: c.lightBorder,
    glassBorder: c.lightGlassBorder,
    glowPurple: c.purpleGlowLight,
    glowPink: c.pinkGlowLight,
    bubbleGradient: [c.plum600, c.rose550] as const,
    bubbleHighlight: c.lightBubbleHighlight,
    navRimGradient: [
      c.glassWhite96,
      c.lightNavPurple,
      c.lightNavPink,
      c.glassWhite88,
    ] as const,
    navInnerGradient: [
      c.glassWhite88,
      c.lightNavInnerPurple,
      c.lightNavInnerPink,
    ] as const,
    navShadow: c.lightNavShadow,
    bubbleShadow: c.lightBubbleShadow,
    trailGradient: [c.lightTrailStart, c.lightTrailEnd] as const,
    activeDot: c.rose100,
    transparent: c.transparent,
  },
  dark: {
    background: c.plum950,
    backgroundGradient: [
      c.darkBackgroundStart,
      c.darkBackgroundMid,
      c.darkBackgroundEnd,
    ] as const,
    surface: c.darkSurface,
    surfaceGlass: c.glassDark78,
    surfaceGlassStrong: c.glassDark90,
    text: c.rose50,
    mutedText: c.darkMutedText,
    primary: '#D66BD0',
    secondary: c.rose650,
    primarySoft: c.darkPrimarySoft,
    activeText: c.white,
    border: c.darkBorder,
    glassBorder: c.darkGlassBorder,
    glowPurple: c.purpleGlowDark,
    glowPink: c.pinkGlowDark,
    bubbleGradient: ['#A64FD1', c.rose600] as const,
    bubbleHighlight: c.darkBubbleHighlight,
    navRimGradient: [
      c.darkNavWhite,
      c.darkNavPurple,
      c.darkNavPink,
      c.darkNavWhiteEnd,
    ] as const,
    navInnerGradient: [
      c.glassDark94,
      c.glassDark92,
      c.glassDarkRose94,
    ] as const,
    navShadow: c.darkNavShadow,
    bubbleShadow: c.darkBubbleShadow,
    trailGradient: [c.darkTrailStart, c.darkTrailEnd] as const,
    activeDot: c.rose200,
    transparent: c.transparent,
  },
} as const;

export type ColorMode = keyof typeof semanticColors;
export type SemanticColors = (typeof semanticColors)[ColorMode];
